<a href="https://colab.research.google.com/github/amitPrakash121/point_cloud_registration/blob/main/point_to_point.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
  from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Data Extraction from d455 - only x, y, z coordinates

In [ ]:
 d455_file_path = '/content/drive/MyDrive/camera_data/D455/Point_Cloud_Textual.ply'

In [ ]:
d455_file = open(d455_file_path, 'r')

In [ ]:
for i in range(3):
  line = d455_file.readline()

In [ ]:
line = d455_file.readline().strip()
split_line = line.split(' ')
split_line

['element', 'vertex', '91754']

In [ ]:
no_vertices = int(split_line[2])
no_vertices

91754

In [ ]:
for i in range(12):
  line = d455_file.readline()

line

'end_header\n'

In [ ]:
import numpy as np

In [ ]:
line = d455_file.readline()

In [ ]:
line_split = line.strip().split(' ')

In [ ]:
line_split

['-1.75586', '1.07031', '-1.90234']

In [ ]:
floats = [[float(i)] for i in line_split]
floats

[[-1.75586], [1.07031], [-1.90234]]

In [ ]:
d455_data = np.array(floats)
d455_data.shape

(3, 1)

In [ ]:
for i in range(no_vertices-1):

  for j in range(2):
    line = d455_file.readline()

  line = d455_file.readline().strip()
  line_split = line.split(' ')
  floats = [[float(j)] for j in line_split]
  new_data = np.array(floats)
  d455_data = np.concatenate((d455_data, new_data), axis=1)   

In [ ]:
d455_data[:,0], d455_data[:, 91753]

(array([-1.75586,  1.07031, -1.90234]),
 array([ 0.617676, -0.34668 , -0.610352]))

In [ ]:
d455_file.close()

# L515 data extraction - only x, y, z coordinates

In [ ]:
l515_file_path = '/content/drive/MyDrive/camera_data/L515/Point_cloud_textual.ply'

In [ ]:
l515_file = open(l515_file_path, 'r')

In [ ]:
for i in range(3):
  line = l515_file.readline()

In [ ]:
line = l515_file.readline().strip()
split_line = line.split(' ')
split_line

['element', 'vertex', '254555']

In [ ]:
no_vertices = int(split_line[2])
no_vertices

254555

In [ ]:
for i in range(12):
  line = l515_file.readline()

line

'end_header\n'

In [ ]:
line = l515_file.readline()

In [ ]:
line_split = line.strip().split(' ')

In [ ]:
line_split

['-1.46191', '1.17969', '-2.12305']

In [ ]:
floats = [[float(i)] for i in line_split]
floats

[[-1.46191], [1.17969], [-2.12305]]

In [ ]:
l515_data = np.array(floats)
l515_data.shape

(3, 1)

In [ ]:
for i in range(no_vertices-1):

  for j in range(2):
    line = l515_file.readline()

  line = l515_file.readline().strip()
  line_split = line.split(' ')
  floats = [[float(j)] for j in line_split]
  new_data = np.array(floats)
  l515_data = np.concatenate((l515_data, new_data), axis=1)

In [ ]:
l515_data[:,0], l515_data[:, 254554]

(array([-1.46191,  1.17969, -2.12305]),
 array([-0.188477, -0.304443, -0.617188]))

In [ ]:
l515_data.shape

(3, 254555)

In [ ]:
l515_file.close()

# Define matching function

In [ ]:
def matching(reading, reference):
  match = []
  for i in range(len(reading[0])):
    dist = np.empty(0)
    for j in range(len(reference[0])):
      distance = ((reading[:,i][0] - reference[:,j][0])**2 +
                  (reading[:,i][0] - reference[:,j][0])**2 +
                  (reading[:,i][0] - reference[:,j][0])**2 )**0.5
      dist = np.append(dist, distance)
    
    min_arg = np.argmin(dist)
    match_list = [i, min_arg]
    match.append(match_list)

  return match


In [ ]:
# Test matching - d455 reference, l515 reading
#match1 = matching(l515_data, d455_data) ---- was not able to do due to large time taken

In [ ]:
#match1.shape

# Random subsampling of both point clouds to 10%

d455_data subsampling

In [ ]:
sub_d455_data = d455_data[:,0]
sub_d455_data.shape

(3,)

In [ ]:
sub_d455_data = np.reshape(sub_d455_data, (3,1))
sub_d455_data

array([[-1.75586],
       [ 1.07031],
       [-1.90234]])

In [ ]:
for i in range(10, len(d455_data[0]), 10):
  temp = d455_data[:,i]
  temp = np.reshape(temp, (3,1))
  sub_d455_data = np.concatenate((sub_d455_data, temp), axis=1)

In [ ]:
sub_d455_data.shape

(3, 9176)

l515_data subsampling

In [ ]:
sub_l515_data = l515_data[:,0]
sub_l515_data.shape

(3,)

In [ ]:
sub_l515_data = np.reshape(sub_l515_data, (3,1))
sub_l515_data

array([[-1.46191],
       [ 1.17969],
       [-2.12305]])

In [ ]:
for i in range(10, len(l515_data[0]), 10):
  temp = l515_data[:,i]
  temp = np.reshape(temp, (3,1))
  sub_l515_data = np.concatenate((sub_l515_data, temp), axis=1)

In [ ]:
sub_l515_data.shape

(3, 25456)

#  Transformation 1

Initial error

d455 as reading and l515 as reference

In [ ]:
Match = matching(sub_d455_data, sub_l515_data)

In [ ]:
Match

[[0, 978],
 [1, 978],
 [2, 978],
 [3, 978],
 [4, 978],
 [5, 52],
 [6, 315],
 [7, 896],
 [8, 107],
 [9, 809],
 [10, 162],
 [11, 322],
 [12, 3996],
 [13, 8718],
 [14, 4851],
 [15, 9751],
 [16, 6750],
 [17, 7906],
 [18, 2036],
 [19, 7658],
 [20, 11181],
 [21, 631],
 [22, 5876],
 [23, 14005],
 [24, 868],
 [25, 12344],
 [26, 6583],
 [27, 3143],
 [28, 1426],
 [29, 455],
 [30, 1240],
 [31, 1048],
 [32, 1987],
 [33, 359],
 [34, 1330],
 [35, 4428],
 [36, 978],
 [37, 978],
 [38, 978],
 [39, 978],
 [40, 978],
 [41, 756],
 [42, 315],
 [43, 896],
 [44, 107],
 [45, 319],
 [46, 162],
 [47, 322],
 [48, 4608],
 [49, 3044],
 [50, 5035],
 [51, 12950],
 [52, 11164],
 [53, 7842],
 [54, 2036],
 [55, 7658],
 [56, 11181],
 [57, 631],
 [58, 18484],
 [59, 14005],
 [60, 2601],
 [61, 12344],
 [62, 6583],
 [63, 3143],
 [64, 1426],
 [65, 455],
 [66, 1240],
 [67, 1048],
 [68, 1358],
 [69, 1695],
 [70, 96],
 [71, 49],
 [72, 4661],
 [73, 5902],
 [74, 7627],
 [75, 978],
 [76, 978],
 [77, 978],
 [78, 978],
 [79, 936],
 

In [ ]:
Match[0][0], Match[0][1]

(0, 978)

In [ ]:
len(Match)

9176

In [ ]:
initial_error = 0
for i in range(len(Match)):
  initial_error += np.linalg.norm((sub_d455_data[:,i] - sub_l515_data[:,Match[i][1]]))

In [ ]:
initial_error

5220.25972347433

Calculate transformation

In [ ]:
mean_p_x, mean_p_y, mean_p_z = 0.0, 0.0, 0.0
for i in range(len(sub_d455_data[0])):
  temp = sub_d455_data[:,i]
  mean_p_x += temp[0]/len(sub_d455_data[0])
  mean_p_y += temp[1]/len(sub_d455_data[0])
  mean_p_z += temp[1]/len(sub_d455_data[0])

mean_p = np.array([[mean_p_x],
                  [mean_p_y],
                  [mean_p_z]])
mean_p

array([[-0.07718891],
       [ 0.1136729 ],
       [ 0.1136729 ]])

In [ ]:
mean_q_x, mean_q_y, mean_q_z = 0.0, 0.0, 0.0
for i in range(len(sub_l515_data[0])):
  temp = sub_l515_data[:,i]
  mean_q_x += temp[0]/len(sub_l515_data[0])
  mean_q_y += temp[1]/len(sub_l515_data[0])
  mean_q_z += temp[1]/len(sub_l515_data[0])

mean_q = np.array([[mean_q_x],
                   [mean_q_y],
                   [mean_q_z]])
mean_q

array([[0.0219483 ],
       [0.11306869],
       [0.11306869]])

In [ ]:
H_matrix = np.array([[0.0, 0.0, 0.0],
                     [0.0, 0.0, 0.0],
                     [0.0, 0.0, 0.0]])
for i in range(len(Match)):
  p = sub_d455_data[:,0]
  p_matrix = np.array([[p[0] - mean_p_x],
                       [p[1] - mean_p_y],
                       [p[2] - mean_p_z]])
  q = sub_l515_data[:,Match[i][1]]
  q_matrix = np.array([q[0] - mean_q_x, q[1] - mean_q_y, q[2] - mean_q_z])
  q_matrix = q_matrix.reshape(1,3)
  temp_matrix = np.matmul(p_matrix, q_matrix)
  H_matrix += temp_matrix

H_matrix

array([[  1443.51112966,  -4431.42782799,  21074.84288681],
       [  -822.62469602,   2525.37157148, -12010.08143775],
       [  1733.59574252,  -5321.95717652,  25309.99391147]])

In [ ]:
u, s, vh = np.linalg.svd(H_matrix)

In [ ]:
u.shape, vh.shape

((3, 3), (3, 3))

In [ ]:
rotation_matrix = np.matmul(vh.transpose(), u.transpose())
rotation_matrix

array([[ 0.54868337,  0.83541066,  0.03218072],
       [-0.71878215,  0.45172611,  0.52848438],
       [ 0.42696462, -0.31310151,  0.84833287]])

In [ ]:
translation_matrix = mean_q - np.matmul(rotation_matrix, mean_p)
translation_matrix

array([[-0.03432106],
       [-0.05383669],
       [ 0.08518432]])

In [ ]:
mean_q - mean_p

array([[ 0.09913721],
       [-0.00060422],
       [-0.00060422]])

Applying rotation to all p vectors

In [ ]:
sub_d455_data_new = np.matmul(rotation_matrix, sub_d455_data)

Applying translation to all data

In [ ]:
for i in range(len(sub_d455_data_new[0])):
  temp = sub_d455_data_new[:,i].reshape(3,1) + translation_matrix
  sub_d455_data_new[0:3,i] = temp[0][0], temp[1][0], temp[2][0]

In [ ]:
sub_d455_data_new

array([[-0.16480252, -0.11648301, -0.06746595, ..., -0.06267787,
        -0.02536223, -0.00959273],
       [ 0.68637412,  0.62814872,  0.57715619, ..., -0.9258412 ,
        -0.94227992, -0.96922023],
       [-2.61343901, -2.59972239, -2.62046737, ..., -0.11012545,
        -0.07482355, -0.06381954]])

# Transformation 2

In [ ]:
new_match = matching(sub_d455_data_new, sub_l515_data)

In [ ]:
error1 = 0
for i in range(len(new_match)):
  error1 += np.linalg.norm((sub_d455_data_new[:,i] - sub_l515_data[:,new_match[i][1]]))

error1

10475.985535297626

In [ ]:
mean_p += translation_matrix
mean_p

array([[-0.11150997],
       [ 0.05983621],
       [ 0.19885722]])

In [ ]:
H_matrix = np.array([[0.0, 0.0, 0.0],
                     [0.0, 0.0, 0.0],
                     [0.0, 0.0, 0.0]])
for i in range(len(new_match)):
  p = sub_d455_data_new[:,0]
  p_matrix = np.array([[p[0] - mean_p_x],
                       [p[1] - mean_p_y],
                       [p[2] - mean_p_z]])
  q = sub_l515_data[:,Match[i][1]]
  q_matrix = np.array([q[0] - mean_q_x, q[1] - mean_q_y, q[2] - mean_q_z])
  q_matrix = q_matrix.reshape(1,3)
  temp_matrix = np.matmul(p_matrix, q_matrix)
  H_matrix += temp_matrix

H_matrix

array([[   75.34008688,  -231.28616793,  1099.9433682 ],
       [ -492.47323803,  1511.84120906, -7189.96612094],
       [ 2345.07903837, -7199.14678588, 34237.47228222]])

In [ ]:
u, s, vh = np.linalg.svd(H_matrix)

In [ ]:
rotation_matrix = np.matmul(vh.transpose(), u.transpose())
rotation_matrix

array([[-0.93238657,  0.32120452,  0.16577978],
       [ 0.32221798,  0.94642148, -0.02149322],
       [ 0.16380126, -0.03337724,  0.98592855]])

In [ ]:
translation_matrix = mean_q - np.matmul(rotation_matrix, mean_p)
translation_matrix

array([[-0.13420826],
       [ 0.09664301],
       [-0.06272768]])

In [ ]:
sub_d455_data_new = np.matmul(rotation_matrix, sub_d455_data)

In [ ]:
for i in range(len(sub_d455_data_new[0])):
  temp = sub_d455_data_new[:,i].reshape(3,1) + translation_matrix
  sub_d455_data_new[0:3,i] = temp[0][0], temp[1][0], temp[2][0]

In [ ]:
sub_d455_data_new

array([[ 1.53135093,  1.46237296,  1.41209778, ..., -0.84486051,
        -0.88121986, -0.91323555],
       [ 0.58472514,  0.61826454,  0.65991236, ..., -0.0571415 ,
        -0.03034823, -0.02202262],
       [-2.26163508, -2.26713647, -2.30135826, ..., -0.58298298,
        -0.55350364, -0.55239657]])